name: CI/CD Pipeline for P2P Payment Splitter

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "prisma/**"
      - "tests/**"
      - "Dockerfile"
      - ".dockerignore"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/deploy.yml"
      - "task-definition.json"
      - "jest.config.js"
      - "tsconfig.json"
      - "tsconfig.spec.json"
      - ".eslintrc.cjs"

# Set this to true to actually perform the deployment
env:
  ENABLE_DEPLOYMENT: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.1

      - name: Install dependencies
        run: pnpm install

      - name: Run CI environment debug script
        run: |
          chmod +x ci-debug.sh
          ./ci-debug.sh
          
      - name: Run linters and tests
        run: |
          pnpm lint
          pnpm test

      - name: Build Docker image
        run: docker build -t p2p-payment-splitter:${{ github.sha }} .

      - name: Configure AWS credentials using OIDC
        if: env.ENABLE_DEPLOYMENT == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: env.ENABLE_DEPLOYMENT == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Define ECR repository and image tag
        if: env.ENABLE_DEPLOYMENT == 'true'
        id: image-details
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY_NAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Tag and push Docker image to Amazon ECR
        if: env.ENABLE_DEPLOYMENT == 'true'
        run: |
          docker tag p2p-payment-splitter:${{ github.sha }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Run Prisma Migrate Deploy
        if: env.ENABLE_DEPLOYMENT == 'true'
        run: npx prisma migrate deploy
        env:
          AWS_DB_DATABASE: ${{ secrets.DATABASE_URL_PROD }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        if: env.ENABLE_DEPLOYMENT == 'true'
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: p2p-payment-splitter-container
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy Amazon ECS task definition
        if: env.ENABLE_DEPLOYMENT == 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_NAME }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
          
      - name: CI Pipeline Completion
        run: echo "CI pipeline completed successfully. Deployment was $([ "$ENABLE_DEPLOYMENT" == "true" ] && echo "executed" || echo "skipped")."
